<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellDataReportingAPIsLib\Models\AccountResponse;
use ShellDataReportingAPIsLib\Models\ErrorStatus;

/**
 * Builder for model AccountResponse
 *
 * @see AccountResponse
 */
class AccountResponseBuilder
{
    /**
     * @var AccountResponse
     */
    private $instance;

    private function __construct(AccountResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new account response Builder object.
     */
    public static function init(): self
    {
        return new self(new AccountResponse());
    }

    /**
     * Sets accounts field.
     */
    public function accounts(?array $value): self
    {
        $this->instance->setAccounts($value);
        return $this;
    }

    /**
     * Sets current page field.
     */
    public function currentPage(?int $value): self
    {
        $this->instance->setCurrentPage($value);
        return $this;
    }

    /**
     * Sets row count field.
     */
    public function rowCount(?int $value): self
    {
        $this->instance->setRowCount($value);
        return $this;
    }

    /**
     * Sets total pages field.
     */
    public function totalPages(?int $value): self
    {
        $this->instance->setTotalPages($value);
        return $this;
    }

    /**
     * Sets error field.
     */
    public function error(?ErrorStatus $value): self
    {
        $this->instance->setError($value);
        return $this;
    }

    /**
     * Sets request id field.
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Initializes a new account response object.
     */
    public function build(): AccountResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
