<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellDataReportingAPIsLib\Models\AuditArrayElements;
use ShellDataReportingAPIsLib\Models\AuditResponseAuditsItems;

/**
 * Builder for model AuditArrayElements
 *
 * @see AuditArrayElements
 */
class AuditArrayElementsBuilder
{
    /**
     * @var AuditArrayElements
     */
    private $instance;

    private function __construct(AuditArrayElements $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Audit Array Elements Builder object.
     */
    public static function init(): self
    {
        return new self(new AuditArrayElements());
    }

    /**
     * Sets Audits field.
     *
     * @param AuditResponseAuditsItems[]|null $value
     */
    public function audits(?array $value): self
    {
        $this->instance->setAudits($value);
        return $this;
    }

    /**
     * Initializes a new Audit Array Elements object.
     */
    public function build(): AuditArrayElements
    {
        return CoreHelper::clone($this->instance);
    }
}
