<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellDataReportingAPIsLib\Models\CardDayTimeRestrictions;

/**
 * Builder for model CardDayTimeRestrictions
 *
 * @see CardDayTimeRestrictions
 */
class CardDayTimeRestrictionsBuilder
{
    /**
     * @var CardDayTimeRestrictions
     */
    private $instance;

    private function __construct(CardDayTimeRestrictions $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Card Day Time Restrictions Builder object.
     */
    public static function init(): self
    {
        return new self(new CardDayTimeRestrictions());
    }

    /**
     * Sets Level field.
     *
     * @param string|null $value
     */
    public function level(?string $value): self
    {
        $this->instance->setLevel($value);
        return $this;
    }

    /**
     * Unsets Level field.
     */
    public function unsetLevel(): self
    {
        $this->instance->unsetLevel();
        return $this;
    }

    /**
     * Sets Monday field.
     *
     * @param bool|null $value
     */
    public function monday(?bool $value): self
    {
        $this->instance->setMonday($value);
        return $this;
    }

    /**
     * Sets Tuesday field.
     *
     * @param bool|null $value
     */
    public function tuesday(?bool $value): self
    {
        $this->instance->setTuesday($value);
        return $this;
    }

    /**
     * Sets Wednesday field.
     *
     * @param bool|null $value
     */
    public function wednesday(?bool $value): self
    {
        $this->instance->setWednesday($value);
        return $this;
    }

    /**
     * Sets Thursday field.
     *
     * @param bool|null $value
     */
    public function thursday(?bool $value): self
    {
        $this->instance->setThursday($value);
        return $this;
    }

    /**
     * Sets Friday field.
     *
     * @param bool|null $value
     */
    public function friday(?bool $value): self
    {
        $this->instance->setFriday($value);
        return $this;
    }

    /**
     * Sets Saturday field.
     *
     * @param bool|null $value
     */
    public function saturday(?bool $value): self
    {
        $this->instance->setSaturday($value);
        return $this;
    }

    /**
     * Sets Sunday field.
     *
     * @param bool|null $value
     */
    public function sunday(?bool $value): self
    {
        $this->instance->setSunday($value);
        return $this;
    }

    /**
     * Sets Time From field.
     *
     * @param string|null $value
     */
    public function timeFrom(?string $value): self
    {
        $this->instance->setTimeFrom($value);
        return $this;
    }

    /**
     * Unsets Time From field.
     */
    public function unsetTimeFrom(): self
    {
        $this->instance->unsetTimeFrom();
        return $this;
    }

    /**
     * Sets Time To field.
     *
     * @param string|null $value
     */
    public function timeTo(?string $value): self
    {
        $this->instance->setTimeTo($value);
        return $this;
    }

    /**
     * Unsets Time To field.
     */
    public function unsetTimeTo(): self
    {
        $this->instance->unsetTimeTo();
        return $this;
    }

    /**
     * Initializes a new Card Day Time Restrictions object.
     */
    public function build(): CardDayTimeRestrictions
    {
        return CoreHelper::clone($this->instance);
    }
}
