<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellDataReportingAPIsLib\Models\CardUsageSummaryResponse;
use ShellDataReportingAPIsLib\Models\ErrorStatus;

/**
 * Builder for model CardUsageSummaryResponse
 *
 * @see CardUsageSummaryResponse
 */
class CardUsageSummaryResponseBuilder
{
    /**
     * @var CardUsageSummaryResponse
     */
    private $instance;

    private function __construct(CardUsageSummaryResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new card usage summary response Builder object.
     */
    public static function init(): self
    {
        return new self(new CardUsageSummaryResponse());
    }

    /**
     * Sets usage summary field.
     */
    public function usageSummary(?array $value): self
    {
        $this->instance->setUsageSummary($value);
        return $this;
    }

    /**
     * Sets request id field.
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Sets error field.
     */
    public function error(?ErrorStatus $value): self
    {
        $this->instance->setError($value);
        return $this;
    }

    /**
     * Initializes a new card usage summary response object.
     */
    public function build(): CardUsageSummaryResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
