<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellDataReportingAPIsLib\Models\CardTypeResponseCustomerCardTypesItems;
use ShellDataReportingAPIsLib\Models\CartTypeAccount;
use ShellDataReportingAPIsLib\Models\PurchaseCategories;

/**
 * Builder for model CardTypeResponseCustomerCardTypesItems
 *
 * @see CardTypeResponseCustomerCardTypesItems
 */
class CardTypeResponseCustomerCardTypesItemsBuilder
{
    /**
     * @var CardTypeResponseCustomerCardTypesItems
     */
    private $instance;

    private function __construct(CardTypeResponseCustomerCardTypesItems $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Card Type Response Customer Card Types Items Builder object.
     */
    public static function init(): self
    {
        return new self(new CardTypeResponseCustomerCardTypesItems());
    }

    /**
     * Sets Card Type Id field.
     *
     * @param int|null $value
     */
    public function cardTypeId(?int $value): self
    {
        $this->instance->setCardTypeId($value);
        return $this;
    }

    /**
     * Sets Token Type Id field.
     *
     * @param int|null $value
     */
    public function tokenTypeId(?int $value): self
    {
        $this->instance->setTokenTypeId($value);
        return $this;
    }

    /**
     * Sets Card Type Name field.
     *
     * @param string|null $value
     */
    public function cardTypeName(?string $value): self
    {
        $this->instance->setCardTypeName($value);
        return $this;
    }

    /**
     * Sets Token Type Name field.
     *
     * @param string|null $value
     */
    public function tokenTypeName(?string $value): self
    {
        $this->instance->setTokenTypeName($value);
        return $this;
    }

    /**
     * Sets PAN Length field.
     *
     * @param int|null $value
     */
    public function pANLength(?int $value): self
    {
        $this->instance->setPANLength($value);
        return $this;
    }

    /**
     * Sets Expiry Period field.
     *
     * @param int|null $value
     */
    public function expiryPeriod(?int $value): self
    {
        $this->instance->setExpiryPeriod($value);
        return $this;
    }

    /**
     * Sets Is National field.
     *
     * @param bool|null $value
     */
    public function isNational(?bool $value): self
    {
        $this->instance->setIsNational($value);
        return $this;
    }

    /**
     * Sets Is International field.
     *
     * @param bool|null $value
     */
    public function isInternational(?bool $value): self
    {
        $this->instance->setIsInternational($value);
        return $this;
    }

    /**
     * Sets Is CRT field.
     *
     * @param bool|null $value
     */
    public function isCRT(?bool $value): self
    {
        $this->instance->setIsCRT($value);
        return $this;
    }

    /**
     * Sets Is Fleet field.
     *
     * @param bool|null $value
     */
    public function isFleet(?bool $value): self
    {
        $this->instance->setIsFleet($value);
        return $this;
    }

    /**
     * Sets Is Shell Sites Only field.
     *
     * @param bool|null $value
     */
    public function isShellSitesOnly(?bool $value): self
    {
        $this->instance->setIsShellSitesOnly($value);
        return $this;
    }

    /**
     * Sets Is Partner Sites Included field.
     *
     * @param bool|null $value
     */
    public function isPartnerSitesIncluded(?bool $value): self
    {
        $this->instance->setIsPartnerSitesIncluded($value);
        return $this;
    }

    /**
     * Sets Can Have PIN field.
     *
     * @param bool|null $value
     */
    public function canHavePIN(?bool $value): self
    {
        $this->instance->setCanHavePIN($value);
        return $this;
    }

    /**
     * Sets Is Virtual field.
     *
     * @param bool|null $value
     */
    public function isVirtual(?bool $value): self
    {
        $this->instance->setIsVirtual($value);
        return $this;
    }

    /**
     * Sets Is Active field.
     *
     * @param bool|null $value
     */
    public function isActive(?bool $value): self
    {
        $this->instance->setIsActive($value);
        return $this;
    }

    /**
     * Sets Is Card Available For Download field.
     *
     * @param bool|null $value
     */
    public function isCardAvailableForDownload(?bool $value): self
    {
        $this->instance->setIsCardAvailableForDownload($value);
        return $this;
    }

    /**
     * Unsets Is Card Available For Download field.
     */
    public function unsetIsCardAvailableForDownload(): self
    {
        $this->instance->unsetIsCardAvailableForDownload();
        return $this;
    }

    /**
     * Sets Col Co Currency Code field.
     *
     * @param string|null $value
     */
    public function colCoCurrencyCode(?string $value): self
    {
        $this->instance->setColCoCurrencyCode($value);
        return $this;
    }

    /**
     * Sets Col Co Currency Symbol field.
     *
     * @param string|null $value
     */
    public function colCoCurrencySymbol(?string $value): self
    {
        $this->instance->setColCoCurrencySymbol($value);
        return $this;
    }

    /**
     * Sets EMV Contactless field.
     *
     * @param bool|null $value
     */
    public function eMVContactless(?bool $value): self
    {
        $this->instance->setEMVContactless($value);
        return $this;
    }

    /**
     * Unsets EMV Contactless field.
     */
    public function unsetEMVContactless(): self
    {
        $this->instance->unsetEMVContactless();
        return $this;
    }

    /**
     * Sets RFID field.
     *
     * @param bool|null $value
     */
    public function rFID(?bool $value): self
    {
        $this->instance->setRFID($value);
        return $this;
    }

    /**
     * Unsets RFID field.
     */
    public function unsetRFID(): self
    {
        $this->instance->unsetRFID();
        return $this;
    }

    /**
     * Sets PIN Change Supported field.
     *
     * @param bool|null $value
     */
    public function pINChangeSupported(?bool $value): self
    {
        $this->instance->setPINChangeSupported($value);
        return $this;
    }

    /**
     * Unsets PIN Change Supported field.
     */
    public function unsetPINChangeSupported(): self
    {
        $this->instance->unsetPINChangeSupported();
        return $this;
    }

    /**
     * Sets Require PIN field.
     *
     * @param bool|null $value
     */
    public function requirePIN(?bool $value): self
    {
        $this->instance->setRequirePIN($value);
        return $this;
    }

    /**
     * Unsets Require PIN field.
     */
    public function unsetRequirePIN(): self
    {
        $this->instance->unsetRequirePIN();
        return $this;
    }

    /**
     * Sets Offline PIN field.
     *
     * @param bool|null $value
     */
    public function offlinePIN(?bool $value): self
    {
        $this->instance->setOfflinePIN($value);
        return $this;
    }

    /**
     * Unsets Offline PIN field.
     */
    public function unsetOfflinePIN(): self
    {
        $this->instance->unsetOfflinePIN();
        return $this;
    }

    /**
     * Sets Medium Type ID field.
     *
     * @param int|null $value
     */
    public function mediumTypeID(?int $value): self
    {
        $this->instance->setMediumTypeID($value);
        return $this;
    }

    /**
     * Sets Medium Type field.
     *
     * @param string|null $value
     */
    public function mediumType(?string $value): self
    {
        $this->instance->setMediumType($value);
        return $this;
    }

    /**
     * Sets Cart Type Accounts field.
     *
     * @param CartTypeAccount[]|null $value
     */
    public function cartTypeAccounts(?array $value): self
    {
        $this->instance->setCartTypeAccounts($value);
        return $this;
    }

    /**
     * Sets Purchase Categories field.
     *
     * @param PurchaseCategories[]|null $value
     */
    public function purchaseCategories(?array $value): self
    {
        $this->instance->setPurchaseCategories($value);
        return $this;
    }

    /**
     * Unsets Purchase Categories field.
     */
    public function unsetPurchaseCategories(): self
    {
        $this->instance->unsetPurchaseCategories();
        return $this;
    }

    /**
     * Initializes a new Card Type Response Customer Card Types Items object.
     */
    public function build(): CardTypeResponseCustomerCardTypesItems
    {
        return CoreHelper::clone($this->instance);
    }
}
