<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellDataReportingAPIsLib\Models\CardUsageSummaryReq;
use ShellDataReportingAPIsLib\Models\CardUsageSummaryRequest;

/**
 * Builder for model CardUsageSummaryReq
 *
 * @see CardUsageSummaryReq
 */
class CardUsageSummaryReqBuilder
{
    /**
     * @var CardUsageSummaryReq
     */
    private $instance;

    private function __construct(CardUsageSummaryReq $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Card Usage Summary Req Builder object.
     */
    public static function init(): self
    {
        return new self(new CardUsageSummaryReq());
    }

    /**
     * Sets Filters field.
     *
     * @param CardUsageSummaryRequest|null $value
     */
    public function filters(?CardUsageSummaryRequest $value): self
    {
        $this->instance->setFilters($value);
        return $this;
    }

    /**
     * Initializes a new Card Usage Summary Req object.
     */
    public function build(): CardUsageSummaryReq
    {
        return CoreHelper::clone($this->instance);
    }
}
