<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellDataReportingAPIsLib\Models\CardUsageSummaryRes;
use ShellDataReportingAPIsLib\Models\CardUsageSummaryResponse;
use ShellDataReportingAPIsLib\Models\Warning;

/**
 * Builder for model CardUsageSummaryRes
 *
 * @see CardUsageSummaryRes
 */
class CardUsageSummaryResBuilder
{
    /**
     * @var CardUsageSummaryRes
     */
    private $instance;

    private function __construct(CardUsageSummaryRes $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Card Usage Summary Res Builder object.
     */
    public static function init(): self
    {
        return new self(new CardUsageSummaryRes());
    }

    /**
     * Sets Request Id field.
     *
     * @param string|null $value
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Sets Status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets Data field.
     *
     * @param CardUsageSummaryResponse[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets Warnings field.
     *
     * @param Warning[]|null $value
     */
    public function warnings(?array $value): self
    {
        $this->instance->setWarnings($value);
        return $this;
    }

    /**
     * Initializes a new Card Usage Summary Res object.
     */
    public function build(): CardUsageSummaryRes
    {
        return CoreHelper::clone($this->instance);
    }
}
