<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellDataReportingAPIsLib\Models\CustomerDetailRequest;
use ShellDataReportingAPIsLib\Models\CustomerReq;

/**
 * Builder for model CustomerReq
 *
 * @see CustomerReq
 */
class CustomerReqBuilder
{
    /**
     * @var CustomerReq
     */
    private $instance;

    private function __construct(CustomerReq $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Customer Req Builder object.
     */
    public static function init(): self
    {
        return new self(new CustomerReq());
    }

    /**
     * Sets Filters field.
     *
     * @param CustomerDetailRequest|null $value
     */
    public function filters(?CustomerDetailRequest $value): self
    {
        $this->instance->setFilters($value);
        return $this;
    }

    /**
     * Initializes a new Customer Req object.
     */
    public function build(): CustomerReq
    {
        return CoreHelper::clone($this->instance);
    }
}
