<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellDataReportingAPIsLib\Models\CustomerPriceListResponse;
use ShellDataReportingAPIsLib\Models\ErrorStatus;

/**
 * Builder for model CustomerPriceListResponse
 *
 * @see CustomerPriceListResponse
 */
class CustomerPriceListResponseBuilder
{
    /**
     * @var CustomerPriceListResponse
     */
    private $instance;

    private function __construct(CustomerPriceListResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new customer price list response Builder object.
     */
    public static function init(): self
    {
        return new self(new CustomerPriceListResponse());
    }

    /**
     * Sets request id field.
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Sets price list field.
     */
    public function priceList(?array $value): self
    {
        $this->instance->setPriceList($value);
        return $this;
    }

    /**
     * Sets error field.
     */
    public function error(?ErrorStatus $value): self
    {
        $this->instance->setError($value);
        return $this;
    }

    /**
     * Initializes a new customer price list response object.
     */
    public function build(): CustomerPriceListResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
