<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellDataReportingAPIsLib\Models\CustomerPriceListResponse;
use ShellDataReportingAPIsLib\Models\PriceList;

/**
 * Builder for model CustomerPriceListResponse
 *
 * @see CustomerPriceListResponse
 */
class CustomerPriceListResponseBuilder
{
    /**
     * @var CustomerPriceListResponse
     */
    private $instance;

    private function __construct(CustomerPriceListResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Customer Price List Response Builder object.
     */
    public static function init(): self
    {
        return new self(new CustomerPriceListResponse());
    }

    /**
     * Sets Price List field.
     *
     * @param PriceList[]|null $value
     */
    public function priceList(?array $value): self
    {
        $this->instance->setPriceList($value);
        return $this;
    }

    /**
     * Initializes a new Customer Price List Response object.
     */
    public function build(): CustomerPriceListResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
