<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellDataReportingAPIsLib\Models\EIDDownloadReq;
use ShellDataReportingAPIsLib\Models\EIDDownloadRequest;

/**
 * Builder for model EIDDownloadRequest
 *
 * @see EIDDownloadRequest
 */
class EIDDownloadRequestBuilder
{
    /**
     * @var EIDDownloadRequest
     */
    private $instance;

    private function __construct(EIDDownloadRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new EID Download Request Builder object.
     */
    public static function init(): self
    {
        return new self(new EIDDownloadRequest());
    }

    /**
     * Sets Filters field.
     *
     * @param EIDDownloadReq|null $value
     */
    public function filters(?EIDDownloadReq $value): self
    {
        $this->instance->setFilters($value);
        return $this;
    }

    /**
     * Initializes a new EID Download Request object.
     */
    public function build(): EIDDownloadRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
