<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellDataReportingAPIsLib\Models\ErrorUserAccess;
use ShellDataReportingAPIsLib\Models\ErrorUserAccessError;

/**
 * Builder for model ErrorUserAccess
 *
 * @see ErrorUserAccess
 */
class ErrorUserAccessBuilder
{
    /**
     * @var ErrorUserAccess
     */
    private $instance;

    private function __construct(ErrorUserAccess $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new error user access Builder object.
     */
    public static function init(): self
    {
        return new self(new ErrorUserAccess());
    }

    /**
     * Sets error field.
     */
    public function error(?ErrorUserAccessError $value): self
    {
        $this->instance->setError($value);
        return $this;
    }

    /**
     * Initializes a new error user access object.
     */
    public function build(): ErrorUserAccess
    {
        return CoreHelper::clone($this->instance);
    }
}
