<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellDataReportingAPIsLib\Models\ErrorDetails;

/**
 * Builder for model ErrorDetails
 *
 * @see ErrorDetails
 */
class ErrorDetailsBuilder
{
    /**
     * @var ErrorDetails
     */
    private $instance;

    private function __construct(ErrorDetails $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new error details Builder object.
     */
    public static function init(): self
    {
        return new self(new ErrorDetails());
    }

    /**
     * Sets code field.
     */
    public function code(?string $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Sets title field.
     */
    public function title(?string $value): self
    {
        $this->instance->setTitle($value);
        return $this;
    }

    /**
     * Sets detail field.
     */
    public function detail(?string $value): self
    {
        $this->instance->setDetail($value);
        return $this;
    }

    /**
     * Sets additional info field.
     */
    public function additionalInfo(?array $value): self
    {
        $this->instance->setAdditionalInfo($value);
        return $this;
    }

    /**
     * Initializes a new error details object.
     */
    public function build(): ErrorDetails
    {
        return CoreHelper::clone($this->instance);
    }
}
