<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellDataReportingAPIsLib\Models\FinanceCurrency2;

/**
 * Builder for model FinanceCurrency2
 *
 * @see FinanceCurrency2
 */
class FinanceCurrency2Builder
{
    /**
     * @var FinanceCurrency2
     */
    private $instance;

    private function __construct(FinanceCurrency2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new finance currency 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new FinanceCurrency2());
    }

    /**
     * Sets currency code field.
     */
    public function currencyCode(?string $value): self
    {
        $this->instance->setCurrencyCode($value);
        return $this;
    }

    /**
     * Unsets currency code field.
     */
    public function unsetCurrencyCode(): self
    {
        $this->instance->unsetCurrencyCode();
        return $this;
    }

    /**
     * Sets currency symbol field.
     */
    public function currencySymbol(?string $value): self
    {
        $this->instance->setCurrencySymbol($value);
        return $this;
    }

    /**
     * Unsets currency symbol field.
     */
    public function unsetCurrencySymbol(): self
    {
        $this->instance->unsetCurrencySymbol();
        return $this;
    }

    /**
     * Sets invoice exchange rate field.
     */
    public function invoiceExchangeRate(?float $value): self
    {
        $this->instance->setInvoiceExchangeRate($value);
        return $this;
    }

    /**
     * Unsets invoice exchange rate field.
     */
    public function unsetInvoiceExchangeRate(): self
    {
        $this->instance->unsetInvoiceExchangeRate();
        return $this;
    }

    /**
     * Sets credit limit exchange rate field.
     */
    public function creditLimitExchangeRate(?float $value): self
    {
        $this->instance->setCreditLimitExchangeRate($value);
        return $this;
    }

    /**
     * Unsets credit limit exchange rate field.
     */
    public function unsetCreditLimitExchangeRate(): self
    {
        $this->instance->unsetCreditLimitExchangeRate();
        return $this;
    }

    /**
     * Initializes a new finance currency 2 object.
     */
    public function build(): FinanceCurrency2
    {
        return CoreHelper::clone($this->instance);
    }
}
