<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellDataReportingAPIsLib\Models\InvoicesSummaries;

/**
 * Builder for model InvoicesSummaries
 *
 * @see InvoicesSummaries
 */
class InvoicesSummariesBuilder
{
    /**
     * @var InvoicesSummaries
     */
    private $instance;

    private function __construct(InvoicesSummaries $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Invoices Summaries Builder object.
     */
    public static function init(): self
    {
        return new self(new InvoicesSummaries());
    }

    /**
     * Sets Amount Due field.
     *
     * @param float|null $value
     */
    public function amountDue(?float $value): self
    {
        $this->instance->setAmountDue($value);
        return $this;
    }

    /**
     * Unsets Amount Due field.
     */
    public function unsetAmountDue(): self
    {
        $this->instance->unsetAmountDue();
        return $this;
    }

    /**
     * Sets Amount Not Overdue field.
     *
     * @param float|null $value
     */
    public function amountNotOverdue(?float $value): self
    {
        $this->instance->setAmountNotOverdue($value);
        return $this;
    }

    /**
     * Unsets Amount Not Overdue field.
     */
    public function unsetAmountNotOverdue(): self
    {
        $this->instance->unsetAmountNotOverdue();
        return $this;
    }

    /**
     * Sets Amount Overdue field.
     *
     * @param float|null $value
     */
    public function amountOverdue(?float $value): self
    {
        $this->instance->setAmountOverdue($value);
        return $this;
    }

    /**
     * Unsets Amount Overdue field.
     */
    public function unsetAmountOverdue(): self
    {
        $this->instance->unsetAmountOverdue();
        return $this;
    }

    /**
     * Sets Amount Paid field.
     *
     * @param float|null $value
     */
    public function amountPaid(?float $value): self
    {
        $this->instance->setAmountPaid($value);
        return $this;
    }

    /**
     * Unsets Amount Paid field.
     */
    public function unsetAmountPaid(): self
    {
        $this->instance->unsetAmountPaid();
        return $this;
    }

    /**
     * Sets Billing Currency Code field.
     *
     * @param string|null $value
     */
    public function billingCurrencyCode(?string $value): self
    {
        $this->instance->setBillingCurrencyCode($value);
        return $this;
    }

    /**
     * Unsets Billing Currency Code field.
     */
    public function unsetBillingCurrencyCode(): self
    {
        $this->instance->unsetBillingCurrencyCode();
        return $this;
    }

    /**
     * Sets Billing Currency Symbol field.
     *
     * @param string|null $value
     */
    public function billingCurrencySymbol(?string $value): self
    {
        $this->instance->setBillingCurrencySymbol($value);
        return $this;
    }

    /**
     * Unsets Billing Currency Symbol field.
     */
    public function unsetBillingCurrencySymbol(): self
    {
        $this->instance->unsetBillingCurrencySymbol();
        return $this;
    }

    /**
     * Sets Outstanding Balance field.
     *
     * @param float|null $value
     */
    public function outstandingBalance(?float $value): self
    {
        $this->instance->setOutstandingBalance($value);
        return $this;
    }

    /**
     * Unsets Outstanding Balance field.
     */
    public function unsetOutstandingBalance(): self
    {
        $this->instance->unsetOutstandingBalance();
        return $this;
    }

    /**
     * Sets Payment Due Date field.
     *
     * @param string|null $value
     */
    public function paymentDueDate(?string $value): self
    {
        $this->instance->setPaymentDueDate($value);
        return $this;
    }

    /**
     * Unsets Payment Due Date field.
     */
    public function unsetPaymentDueDate(): self
    {
        $this->instance->unsetPaymentDueDate();
        return $this;
    }

    /**
     * Sets Summary Document Date field.
     *
     * @param string|null $value
     */
    public function summaryDocumentDate(?string $value): self
    {
        $this->instance->setSummaryDocumentDate($value);
        return $this;
    }

    /**
     * Unsets Summary Document Date field.
     */
    public function unsetSummaryDocumentDate(): self
    {
        $this->instance->unsetSummaryDocumentDate();
        return $this;
    }

    /**
     * Sets Total Billing Documents field.
     *
     * @param int|null $value
     */
    public function totalBillingDocuments(?int $value): self
    {
        $this->instance->setTotalBillingDocuments($value);
        return $this;
    }

    /**
     * Unsets Total Billing Documents field.
     */
    public function unsetTotalBillingDocuments(): self
    {
        $this->instance->unsetTotalBillingDocuments();
        return $this;
    }

    /**
     * Sets Total Gross Amount Billing Currency field.
     *
     * @param float|null $value
     */
    public function totalGrossAmountBillingCurrency(?float $value): self
    {
        $this->instance->setTotalGrossAmountBillingCurrency($value);
        return $this;
    }

    /**
     * Unsets Total Gross Amount Billing Currency field.
     */
    public function unsetTotalGrossAmountBillingCurrency(): self
    {
        $this->instance->unsetTotalGrossAmountBillingCurrency();
        return $this;
    }

    /**
     * Sets Total Net Amount Billing Currency field.
     *
     * @param float|null $value
     */
    public function totalNetAmountBillingCurrency(?float $value): self
    {
        $this->instance->setTotalNetAmountBillingCurrency($value);
        return $this;
    }

    /**
     * Unsets Total Net Amount Billing Currency field.
     */
    public function unsetTotalNetAmountBillingCurrency(): self
    {
        $this->instance->unsetTotalNetAmountBillingCurrency();
        return $this;
    }

    /**
     * Sets Total Summary Documents field.
     *
     * @param int|null $value
     */
    public function totalSummaryDocuments(?int $value): self
    {
        $this->instance->setTotalSummaryDocuments($value);
        return $this;
    }

    /**
     * Unsets Total Summary Documents field.
     */
    public function unsetTotalSummaryDocuments(): self
    {
        $this->instance->unsetTotalSummaryDocuments();
        return $this;
    }

    /**
     * Sets Total VAT Amount Billing Currency field.
     *
     * @param float|null $value
     */
    public function totalVATAmountBillingCurrency(?float $value): self
    {
        $this->instance->setTotalVATAmountBillingCurrency($value);
        return $this;
    }

    /**
     * Unsets Total VAT Amount Billing Currency field.
     */
    public function unsetTotalVATAmountBillingCurrency(): self
    {
        $this->instance->unsetTotalVATAmountBillingCurrency();
        return $this;
    }

    /**
     * Initializes a new Invoices Summaries object.
     */
    public function build(): InvoicesSummaries
    {
        return CoreHelper::clone($this->instance);
    }
}
