<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellDataReportingAPIsLib\Models\PricingHistory;

/**
 * Builder for model PricingHistory
 *
 * @see PricingHistory
 */
class PricingHistoryBuilder
{
    /**
     * @var PricingHistory
     */
    private $instance;

    private function __construct(PricingHistory $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new pricing history Builder object.
     */
    public static function init(): self
    {
        return new self(new PricingHistory());
    }

    /**
     * Sets from date field.
     */
    public function fromDate(?string $value): self
    {
        $this->instance->setFromDate($value);
        return $this;
    }

    /**
     * Unsets from date field.
     */
    public function unsetFromDate(): self
    {
        $this->instance->unsetFromDate();
        return $this;
    }

    /**
     * Sets to date field.
     */
    public function toDate(?string $value): self
    {
        $this->instance->setToDate($value);
        return $this;
    }

    /**
     * Unsets to date field.
     */
    public function unsetToDate(): self
    {
        $this->instance->unsetToDate();
        return $this;
    }

    /**
     * Sets fees rule id field.
     */
    public function feesRuleID(?int $value): self
    {
        $this->instance->setFeesRuleID($value);
        return $this;
    }

    /**
     * Unsets fees rule id field.
     */
    public function unsetFeesRuleID(): self
    {
        $this->instance->unsetFeesRuleID();
        return $this;
    }

    /**
     * Sets fees rule description field.
     */
    public function feesRuleDescription(?string $value): self
    {
        $this->instance->setFeesRuleDescription($value);
        return $this;
    }

    /**
     * Unsets fees rule description field.
     */
    public function unsetFeesRuleDescription(): self
    {
        $this->instance->unsetFeesRuleDescription();
        return $this;
    }

    /**
     * Sets total volume field.
     */
    public function totalVolume(?float $value): self
    {
        $this->instance->setTotalVolume($value);
        return $this;
    }

    /**
     * Unsets total volume field.
     */
    public function unsetTotalVolume(): self
    {
        $this->instance->unsetTotalVolume();
        return $this;
    }

    /**
     * Initializes a new pricing history object.
     */
    public function build(): PricingHistory
    {
        return CoreHelper::clone($this->instance);
    }
}
