<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellDataReportingAPIsLib\Models\RecentTransactionsResponse;

/**
 * Builder for model RecentTransactionsResponse
 *
 * @see RecentTransactionsResponse
 */
class RecentTransactionsResponseBuilder
{
    /**
     * @var RecentTransactionsResponse
     */
    private $instance;

    private function __construct(RecentTransactionsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new recent transactions response Builder object.
     */
    public static function init(): self
    {
        return new self(new RecentTransactionsResponse());
    }

    /**
     * Sets request id field.
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Sets status field.
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets page field.
     */
    public function page(?int $value): self
    {
        $this->instance->setPage($value);
        return $this;
    }

    /**
     * Sets row count field.
     */
    public function rowCount(?int $value): self
    {
        $this->instance->setRowCount($value);
        return $this;
    }

    /**
     * Sets total pages field.
     */
    public function totalPages(?int $value): self
    {
        $this->instance->setTotalPages($value);
        return $this;
    }

    /**
     * Sets data field.
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new recent transactions response object.
     */
    public function build(): RecentTransactionsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
