<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellDataReportingAPIsLib\Models\SearchSOAReq;

/**
 * Builder for model SearchSOAReq
 *
 * @see SearchSOAReq
 */
class SearchSOAReqBuilder
{
    /**
     * @var SearchSOAReq
     */
    private $instance;

    private function __construct(SearchSOAReq $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new search soareq Builder object.
     */
    public static function init(): self
    {
        return new self(new SearchSOAReq());
    }

    /**
     * Sets col co code field.
     */
    public function colCoCode(?int $value): self
    {
        $this->instance->setColCoCode($value);
        return $this;
    }

    /**
     * Unsets col co code field.
     */
    public function unsetColCoCode(): self
    {
        $this->instance->unsetColCoCode();
        return $this;
    }

    /**
     * Sets payer number field.
     */
    public function payerNumber(?string $value): self
    {
        $this->instance->setPayerNumber($value);
        return $this;
    }

    /**
     * Unsets payer number field.
     */
    public function unsetPayerNumber(): self
    {
        $this->instance->unsetPayerNumber();
        return $this;
    }

    /**
     * Sets invoice number field.
     */
    public function invoiceNumber(?string $value): self
    {
        $this->instance->setInvoiceNumber($value);
        return $this;
    }

    /**
     * Unsets invoice number field.
     */
    public function unsetInvoiceNumber(): self
    {
        $this->instance->unsetInvoiceNumber();
        return $this;
    }

    /**
     * Sets from date field.
     */
    public function fromDate(?string $value): self
    {
        $this->instance->setFromDate($value);
        return $this;
    }

    /**
     * Unsets from date field.
     */
    public function unsetFromDate(): self
    {
        $this->instance->unsetFromDate();
        return $this;
    }

    /**
     * Sets to date field.
     */
    public function toDate(?string $value): self
    {
        $this->instance->setToDate($value);
        return $this;
    }

    /**
     * Unsets to date field.
     */
    public function unsetToDate(): self
    {
        $this->instance->unsetToDate();
        return $this;
    }

    /**
     * Sets period field.
     */
    public function period(?int $value): self
    {
        $this->instance->setPeriod($value);
        return $this;
    }

    /**
     * Unsets period field.
     */
    public function unsetPeriod(): self
    {
        $this->instance->unsetPeriod();
        return $this;
    }

    /**
     * Sets invoice date field.
     */
    public function invoiceDate(?string $value): self
    {
        $this->instance->setInvoiceDate($value);
        return $this;
    }

    /**
     * Unsets invoice date field.
     */
    public function unsetInvoiceDate(): self
    {
        $this->instance->unsetInvoiceDate();
        return $this;
    }

    /**
     * Sets invoice status field.
     */
    public function invoiceStatus(?array $value): self
    {
        $this->instance->setInvoiceStatus($value);
        return $this;
    }

    /**
     * Sets sort by field.
     */
    public function sortBy(?array $value): self
    {
        $this->instance->setSortBy($value);
        return $this;
    }

    /**
     * Sets col co id field.
     */
    public function colCoId(?int $value): self
    {
        $this->instance->setColCoId($value);
        return $this;
    }

    /**
     * Unsets col co id field.
     */
    public function unsetColCoId(): self
    {
        $this->instance->unsetColCoId();
        return $this;
    }

    /**
     * Sets payer id field.
     */
    public function payerId(?int $value): self
    {
        $this->instance->setPayerId($value);
        return $this;
    }

    /**
     * Unsets payer id field.
     */
    public function unsetPayerId(): self
    {
        $this->instance->unsetPayerId();
        return $this;
    }

    /**
     * Initializes a new search soareq object.
     */
    public function build(): SearchSOAReq
    {
        return CoreHelper::clone($this->instance);
    }
}
