<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellDataReportingAPIsLib\Models\LastStatementOfAccount;
use ShellDataReportingAPIsLib\Models\StatementOfAccountResp;

/**
 * Builder for model StatementOfAccountResp
 *
 * @see StatementOfAccountResp
 */
class StatementOfAccountRespBuilder
{
    /**
     * @var StatementOfAccountResp
     */
    private $instance;

    private function __construct(StatementOfAccountResp $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new statement of account resp Builder object.
     */
    public static function init(): self
    {
        return new self(new StatementOfAccountResp());
    }

    /**
     * Sets last statement of account field.
     */
    public function lastStatementOfAccount(?LastStatementOfAccount $value): self
    {
        $this->instance->setLastStatementOfAccount($value);
        return $this;
    }

    /**
     * Sets monthly invoice trend field.
     */
    public function monthlyInvoiceTrend(?array $value): self
    {
        $this->instance->setMonthlyInvoiceTrend($value);
        return $this;
    }

    /**
     * Unsets monthly invoice trend field.
     */
    public function unsetMonthlyInvoiceTrend(): self
    {
        $this->instance->unsetMonthlyInvoiceTrend();
        return $this;
    }

    /**
     * Sets past statement of accounts field.
     */
    public function pastStatementOfAccounts(?array $value): self
    {
        $this->instance->setPastStatementOfAccounts($value);
        return $this;
    }

    /**
     * Sets payments since last soa field.
     */
    public function paymentsSinceLastSOA(?array $value): self
    {
        $this->instance->setPaymentsSinceLastSOA($value);
        return $this;
    }

    /**
     * Unsets payments since last soa field.
     */
    public function unsetPaymentsSinceLastSOA(): self
    {
        $this->instance->unsetPaymentsSinceLastSOA();
        return $this;
    }

    /**
     * Sets invoices summaries field.
     */
    public function invoicesSummaries(?array $value): self
    {
        $this->instance->setInvoicesSummaries($value);
        return $this;
    }

    /**
     * Unsets invoices summaries field.
     */
    public function unsetInvoicesSummaries(): self
    {
        $this->instance->unsetInvoicesSummaries();
        return $this;
    }

    /**
     * Initializes a new statement of account resp object.
     */
    public function build(): StatementOfAccountResp
    {
        return CoreHelper::clone($this->instance);
    }
}
