<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellDataReportingAPIsLib\Models\StatementOfAccountResp;
use ShellDataReportingAPIsLib\Models\StatementOfAccountResponse;

/**
 * Builder for model StatementOfAccountResponse
 *
 * @see StatementOfAccountResponse
 */
class StatementOfAccountResponseBuilder
{
    /**
     * @var StatementOfAccountResponse
     */
    private $instance;

    private function __construct(StatementOfAccountResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Statement Of Account Response Builder object.
     */
    public static function init(): self
    {
        return new self(new StatementOfAccountResponse());
    }

    /**
     * Sets Request Id field.
     *
     * @param string|null $value
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Sets Status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets Data field.
     *
     * @param StatementOfAccountResp[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new Statement Of Account Response object.
     */
    public function build(): StatementOfAccountResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
