<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellDataReportingAPIsLib\Models\CardExceptions;
use ShellDataReportingAPIsLib\Models\ErrorStatus;
use ShellDataReportingAPIsLib\Models\TransactionExceptions;
use ShellDataReportingAPIsLib\Models\TransactionExceptionsResponse;

/**
 * Builder for model TransactionExceptionsResponse
 *
 * @see TransactionExceptionsResponse
 */
class TransactionExceptionsResponseBuilder
{
    /**
     * @var TransactionExceptionsResponse
     */
    private $instance;

    private function __construct(TransactionExceptionsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Transaction Exceptions Response Builder object.
     */
    public static function init(): self
    {
        return new self(new TransactionExceptionsResponse());
    }

    /**
     * Sets Card Exceptions field.
     *
     * @param CardExceptions[]|null $value
     */
    public function cardExceptions(?array $value): self
    {
        $this->instance->setCardExceptions($value);
        return $this;
    }

    /**
     * Sets Transaction Exceptions field.
     *
     * @param TransactionExceptions[]|null $value
     */
    public function transactionExceptions(?array $value): self
    {
        $this->instance->setTransactionExceptions($value);
        return $this;
    }

    /**
     * Unsets Transaction Exceptions field.
     */
    public function unsetTransactionExceptions(): self
    {
        $this->instance->unsetTransactionExceptions();
        return $this;
    }

    /**
     * Sets Error field.
     *
     * @param ErrorStatus|null $value
     */
    public function error(?ErrorStatus $value): self
    {
        $this->instance->setError($value);
        return $this;
    }

    /**
     * Sets Request Id field.
     *
     * @param string|null $value
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Initializes a new Transaction Exceptions Response object.
     */
    public function build(): TransactionExceptionsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
