<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellDataReportingAPIsLib\Models\TransactionFeesRequest;
use ShellDataReportingAPIsLib\Models\TransactionFeesSummaryReq;

/**
 * Builder for model TransactionFeesSummaryReq
 *
 * @see TransactionFeesSummaryReq
 */
class TransactionFeesSummaryReqBuilder
{
    /**
     * @var TransactionFeesSummaryReq
     */
    private $instance;

    private function __construct(TransactionFeesSummaryReq $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Transaction Fees Summary Req Builder object.
     */
    public static function init(): self
    {
        return new self(new TransactionFeesSummaryReq());
    }

    /**
     * Sets Filters field.
     *
     * @param TransactionFeesRequest|null $value
     */
    public function filters(?TransactionFeesRequest $value): self
    {
        $this->instance->setFilters($value);
        return $this;
    }

    /**
     * Initializes a new Transaction Fees Summary Req object.
     */
    public function build(): TransactionFeesSummaryReq
    {
        return CoreHelper::clone($this->instance);
    }
}
