<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellDataReportingAPIsLib\Models\VolumeBasedBonusReq;
use ShellDataReportingAPIsLib\Models\VolumeBasedBonusRequest;

/**
 * Builder for model VolumeBasedBonusReq
 *
 * @see VolumeBasedBonusReq
 */
class VolumeBasedBonusReqBuilder
{
    /**
     * @var VolumeBasedBonusReq
     */
    private $instance;

    private function __construct(VolumeBasedBonusReq $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Volume Based Bonus Req Builder object.
     */
    public static function init(): self
    {
        return new self(new VolumeBasedBonusReq());
    }

    /**
     * Sets Filters field.
     *
     * @param VolumeBasedBonusRequest|null $value
     */
    public function filters(?VolumeBasedBonusRequest $value): self
    {
        $this->instance->setFilters($value);
        return $this;
    }

    /**
     * Initializes a new Volume Based Bonus Req object.
     */
    public function build(): VolumeBasedBonusReq
    {
        return CoreHelper::clone($this->instance);
    }
}
