<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellDataReportingAPIsLib\Models\BonusConfiguration;
use ShellDataReportingAPIsLib\Models\BonusHistory;
use ShellDataReportingAPIsLib\Models\CurrentVolume;
use ShellDataReportingAPIsLib\Models\VolumeBasedBonusResponse;

/**
 * Builder for model VolumeBasedBonusResponse
 *
 * @see VolumeBasedBonusResponse
 */
class VolumeBasedBonusResponseBuilder
{
    /**
     * @var VolumeBasedBonusResponse
     */
    private $instance;

    private function __construct(VolumeBasedBonusResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Volume Based Bonus Response Builder object.
     */
    public static function init(): self
    {
        return new self(new VolumeBasedBonusResponse());
    }

    /**
     * Sets Configuration field.
     *
     * @param BonusConfiguration[]|null $value
     */
    public function configuration(?array $value): self
    {
        $this->instance->setConfiguration($value);
        return $this;
    }

    /**
     * Sets Current Period Consumption field.
     *
     * @param CurrentVolume[]|null $value
     */
    public function currentPeriodConsumption(?array $value): self
    {
        $this->instance->setCurrentPeriodConsumption($value);
        return $this;
    }

    /**
     * Sets Historical Bonus Paid field.
     *
     * @param BonusHistory[]|null $value
     */
    public function historicalBonusPaid(?array $value): self
    {
        $this->instance->setHistoricalBonusPaid($value);
        return $this;
    }

    /**
     * Initializes a new Volume Based Bonus Response object.
     */
    public function build(): VolumeBasedBonusResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
