<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellDataReportingAPIsLib\Models\BonusConfiguration;
use ShellDataReportingAPIsLib\Models\PricingCurrentVolume;
use ShellDataReportingAPIsLib\Models\PricingHistory;
use ShellDataReportingAPIsLib\Models\VolumeBasedPricingResponse;
use ShellDataReportingAPIsLib\Models\Warning;

/**
 * Builder for model VolumeBasedPricingResponse
 *
 * @see VolumeBasedPricingResponse
 */
class VolumeBasedPricingResponseBuilder
{
    /**
     * @var VolumeBasedPricingResponse
     */
    private $instance;

    private function __construct(VolumeBasedPricingResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Volume Based Pricing Response Builder object.
     */
    public static function init(): self
    {
        return new self(new VolumeBasedPricingResponse());
    }

    /**
     * Sets Configuration field.
     *
     * @param BonusConfiguration[]|null $value
     */
    public function configuration(?array $value): self
    {
        $this->instance->setConfiguration($value);
        return $this;
    }

    /**
     * Sets Current Period Consumption field.
     *
     * @param PricingCurrentVolume[]|null $value
     */
    public function currentPeriodConsumption(?array $value): self
    {
        $this->instance->setCurrentPeriodConsumption($value);
        return $this;
    }

    /**
     * Sets History field.
     *
     * @param PricingHistory[]|null $value
     */
    public function history(?array $value): self
    {
        $this->instance->setHistory($value);
        return $this;
    }

    /**
     * Sets Warnings field.
     *
     * @param Warning[]|null $value
     */
    public function warnings(?array $value): self
    {
        $this->instance->setWarnings($value);
        return $this;
    }

    /**
     * Initializes a new Volume Based Pricing Response object.
     */
    public function build(): VolumeBasedPricingResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
