<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Exceptions;

use ShellDataReportingAPIsLib\ApiHelper;

class ErrorUserAccessError1Exception extends ApiException
{
    /**
     * @var \ShellDataReportingAPIsLib\Models\ErrorUserAccessError|null
     */
    private $error;

    /**
     * Returns Error.
     */
    public function getError(): ?\ShellDataReportingAPIsLib\Models\ErrorUserAccessError
    {
        return $this->error;
    }

    /**
     * Sets Error.
     *
     * @maps Error
     */
    public function setError(?\ShellDataReportingAPIsLib\Models\ErrorUserAccessError $error): void
    {
        $this->error = $error;
    }

    /**
     * Converts the ErrorUserAccessError1Exception object to a human-readable string representation.
     *
     * @return string The string representation of the ErrorUserAccessError1Exception object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ErrorUserAccessError1Exception',
            ['error' => $this->error],
            parent::__toString()
        );
    }
}
