<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models;

use stdClass;

class AccountResponse implements \JsonSerializable
{
    /**
     * @var AccountResponseAccountsItems[]|null
     */
    private $accounts;

    /**
     * @var int|null
     */
    private $currentPage;

    /**
     * @var int|null
     */
    private $rowCount;

    /**
     * @var int|null
     */
    private $totalPages;

    /**
     * @var ErrorStatus|null
     */
    private $error;

    /**
     * @var string|null
     */
    private $requestId;

    /**
     * Returns Accounts.
     *
     * @return AccountResponseAccountsItems[]|null
     */
    public function getAccounts(): ?array
    {
        return $this->accounts;
    }

    /**
     * Sets Accounts.
     *
     * @maps Accounts
     *
     * @param AccountResponseAccountsItems[]|null $accounts
     */
    public function setAccounts(?array $accounts): void
    {
        $this->accounts = $accounts;
    }

    /**
     * Returns Current Page.
     * current page
     */
    public function getCurrentPage(): ?int
    {
        return $this->currentPage;
    }

    /**
     * Sets Current Page.
     * current page
     *
     * @maps CurrentPage
     */
    public function setCurrentPage(?int $currentPage): void
    {
        $this->currentPage = $currentPage;
    }

    /**
     * Returns Row Count.
     * Total row count matched for the given input criteria
     */
    public function getRowCount(): ?int
    {
        return $this->rowCount;
    }

    /**
     * Sets Row Count.
     * Total row count matched for the given input criteria
     *
     * @maps RowCount
     */
    public function setRowCount(?int $rowCount): void
    {
        $this->rowCount = $rowCount;
    }

    /**
     * Returns Total Pages.
     * Calculated page count based on page size from the incoming API request and total number of rows
     * matched for the given input criteria.
     */
    public function getTotalPages(): ?int
    {
        return $this->totalPages;
    }

    /**
     * Sets Total Pages.
     * Calculated page count based on page size from the incoming API request and total number of rows
     * matched for the given input criteria.
     *
     * @maps TotalPages
     */
    public function setTotalPages(?int $totalPages): void
    {
        $this->totalPages = $totalPages;
    }

    /**
     * Returns Error.
     */
    public function getError(): ?ErrorStatus
    {
        return $this->error;
    }

    /**
     * Sets Error.
     *
     * @maps Error
     */
    public function setError(?ErrorStatus $error): void
    {
        $this->error = $error;
    }

    /**
     * Returns Request Id.
     * API Request ID
     */
    public function getRequestId(): ?string
    {
        return $this->requestId;
    }

    /**
     * Sets Request Id.
     * API Request ID
     *
     * @maps RequestId
     */
    public function setRequestId(?string $requestId): void
    {
        $this->requestId = $requestId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->accounts)) {
            $json['Accounts']    = $this->accounts;
        }
        if (isset($this->currentPage)) {
            $json['CurrentPage'] = $this->currentPage;
        }
        if (isset($this->rowCount)) {
            $json['RowCount']    = $this->rowCount;
        }
        if (isset($this->totalPages)) {
            $json['TotalPages']  = $this->totalPages;
        }
        if (isset($this->error)) {
            $json['Error']       = $this->error;
        }
        if (isset($this->requestId)) {
            $json['RequestId']   = $this->requestId;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
