<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models;

use ShellDataReportingAPIsLib\ApiHelper;
use stdClass;

class CartTypeAccount implements \JsonSerializable
{
    /**
     * @var array
     */
    private $accountId = [];

    /**
     * @var string|null
     */
    private $accountNumber;

    /**
     * @var bool|null
     */
    private $isDefault;

    /**
     * @var int|null
     */
    private $customerCardTypeId;

    /**
     * @var bool|null
     */
    private $isVisibleToCustomers;

    /**
     * @var string|null
     */
    private $embossAccountName;

    /**
     * @var int|null
     */
    private $defaultPurchaseCategoryId;

    /**
     * @var CardUsageRestrictions|null
     */
    private $usageRestrictions;

    /**
     * @var CardDayTimeRestrictions|null
     */
    private $dayTimeRestrictions;

    /**
     * Returns Account Id.
     * Account Id of the customer.
     */
    public function getAccountId(): ?int
    {
        if (count($this->accountId) == 0) {
            return null;
        }
        return $this->accountId['value'];
    }

    /**
     * Sets Account Id.
     * Account Id of the customer.
     *
     * @maps AccountId
     */
    public function setAccountId(?int $accountId): void
    {
        $this->accountId['value'] = $accountId;
    }

    /**
     * Unsets Account Id.
     * Account Id of the customer.
     */
    public function unsetAccountId(): void
    {
        $this->accountId = [];
    }

    /**
     * Returns Account Number.
     * Account Number of the customer.
     */
    public function getAccountNumber(): ?string
    {
        return $this->accountNumber;
    }

    /**
     * Sets Account Number.
     * Account Number of the customer.
     *
     * @maps AccountNumber
     */
    public function setAccountNumber(?string $accountNumber): void
    {
        $this->accountNumber = $accountNumber;
    }

    /**
     * Returns Is Default.
     * Whether card type is default or not.
     */
    public function getIsDefault(): ?bool
    {
        return $this->isDefault;
    }

    /**
     * Sets Is Default.
     * Whether card type is default or not.
     *
     * @maps IsDefault
     */
    public function setIsDefault(?bool $isDefault): void
    {
        $this->isDefault = $isDefault;
    }

    /**
     * Returns Customer Card Type Id.
     * Customer Card Type Id in Cards Platform.
     */
    public function getCustomerCardTypeId(): ?int
    {
        return $this->customerCardTypeId;
    }

    /**
     * Sets Customer Card Type Id.
     * Customer Card Type Id in Cards Platform.
     *
     * @maps CustomerCardTypeId
     */
    public function setCustomerCardTypeId(?int $customerCardTypeId): void
    {
        $this->customerCardTypeId = $customerCardTypeId;
    }

    /**
     * Returns Is Visible to Customers.
     * True/False – Whether the card type can be used for card ordering. <br><br> Note -
     * IsVisibleToCustomers will be set as ‘false’ when the card type is not active or. configured in MS to
     * be not visible.
     */
    public function getIsVisibleToCustomers(): ?bool
    {
        return $this->isVisibleToCustomers;
    }

    /**
     * Sets Is Visible to Customers.
     * True/False – Whether the card type can be used for card ordering. <br><br> Note -
     * IsVisibleToCustomers will be set as ‘false’ when the card type is not active or. configured in MS to
     * be not visible.
     *
     * @maps IsVisibleToCustomers
     */
    public function setIsVisibleToCustomers(?bool $isVisibleToCustomers): void
    {
        $this->isVisibleToCustomers = $isVisibleToCustomers;
    }

    /**
     * Returns Emboss Account Name.
     * Default Name to be embossed on the card.
     */
    public function getEmbossAccountName(): ?string
    {
        return $this->embossAccountName;
    }

    /**
     * Sets Emboss Account Name.
     * Default Name to be embossed on the card.
     *
     * @maps EmbossAccountName
     */
    public function setEmbossAccountName(?string $embossAccountName): void
    {
        $this->embossAccountName = $embossAccountName;
    }

    /**
     * Returns Default Purchase Category Id.
     * Default Purchase category of the card type.
     */
    public function getDefaultPurchaseCategoryId(): ?int
    {
        return $this->defaultPurchaseCategoryId;
    }

    /**
     * Sets Default Purchase Category Id.
     * Default Purchase category of the card type.
     *
     * @maps DefaultPurchaseCategoryId
     */
    public function setDefaultPurchaseCategoryId(?int $defaultPurchaseCategoryId): void
    {
        $this->defaultPurchaseCategoryId = $defaultPurchaseCategoryId;
    }

    /**
     * Returns Usage Restrictions.
     */
    public function getUsageRestrictions(): ?CardUsageRestrictions
    {
        return $this->usageRestrictions;
    }

    /**
     * Sets Usage Restrictions.
     *
     * @maps UsageRestrictions
     */
    public function setUsageRestrictions(?CardUsageRestrictions $usageRestrictions): void
    {
        $this->usageRestrictions = $usageRestrictions;
    }

    /**
     * Returns Day Time Restrictions.
     */
    public function getDayTimeRestrictions(): ?CardDayTimeRestrictions
    {
        return $this->dayTimeRestrictions;
    }

    /**
     * Sets Day Time Restrictions.
     *
     * @maps DayTimeRestrictions
     */
    public function setDayTimeRestrictions(?CardDayTimeRestrictions $dayTimeRestrictions): void
    {
        $this->dayTimeRestrictions = $dayTimeRestrictions;
    }

    /**
     * Converts the CartTypeAccount object to a human-readable string representation.
     *
     * @return string The string representation of the CartTypeAccount object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CartTypeAccount',
            [
                'accountId' => $this->getAccountId(),
                'accountNumber' => $this->accountNumber,
                'isDefault' => $this->isDefault,
                'customerCardTypeId' => $this->customerCardTypeId,
                'isVisibleToCustomers' => $this->isVisibleToCustomers,
                'embossAccountName' => $this->embossAccountName,
                'defaultPurchaseCategoryId' => $this->defaultPurchaseCategoryId,
                'usageRestrictions' => $this->usageRestrictions,
                'dayTimeRestrictions' => $this->dayTimeRestrictions
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->accountId)) {
            $json['AccountId']                 = $this->accountId['value'];
        }
        if (isset($this->accountNumber)) {
            $json['AccountNumber']             = $this->accountNumber;
        }
        if (isset($this->isDefault)) {
            $json['IsDefault']                 = $this->isDefault;
        }
        if (isset($this->customerCardTypeId)) {
            $json['CustomerCardTypeId']        = $this->customerCardTypeId;
        }
        if (isset($this->isVisibleToCustomers)) {
            $json['IsVisibleToCustomers']      = $this->isVisibleToCustomers;
        }
        if (isset($this->embossAccountName)) {
            $json['EmbossAccountName']         = $this->embossAccountName;
        }
        if (isset($this->defaultPurchaseCategoryId)) {
            $json['DefaultPurchaseCategoryId'] = $this->defaultPurchaseCategoryId;
        }
        if (isset($this->usageRestrictions)) {
            $json['UsageRestrictions']         = $this->usageRestrictions;
        }
        if (isset($this->dayTimeRestrictions)) {
            $json['DayTimeRestrictions']       = $this->dayTimeRestrictions;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
