<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models;

use ShellDataReportingAPIsLib\ApiHelper;
use stdClass;

class CustomerPriceListRes implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $requestId;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var CustomerPriceListResponse[]|null
     */
    private $data;

    /**
     * Returns Request Id.
     * Unique identifier for the request. This will be played back in the response from the request.
     */
    public function getRequestId(): ?string
    {
        return $this->requestId;
    }

    /**
     * Sets Request Id.
     * Unique identifier for the request. This will be played back in the response from the request.
     *
     * @maps RequestId
     */
    public function setRequestId(?string $requestId): void
    {
        $this->requestId = $requestId;
    }

    /**
     * Returns Status.
     * Status of the request
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * Status of the request
     *
     * @maps Status
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Data.
     *
     * @return CustomerPriceListResponse[]|null
     */
    public function getData(): ?array
    {
        return $this->data;
    }

    /**
     * Sets Data.
     *
     * @maps Data
     *
     * @param CustomerPriceListResponse[]|null $data
     */
    public function setData(?array $data): void
    {
        $this->data = $data;
    }

    /**
     * Converts the CustomerPriceListRes object to a human-readable string representation.
     *
     * @return string The string representation of the CustomerPriceListRes object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CustomerPriceListRes',
            ['requestId' => $this->requestId, 'status' => $this->status, 'data' => $this->data]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->requestId)) {
            $json['RequestId'] = $this->requestId;
        }
        if (isset($this->status)) {
            $json['Status']    = $this->status;
        }
        if (isset($this->data)) {
            $json['Data']      = $this->data;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
