<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models;

use stdClass;

class FeeSummaryResponse implements \JsonSerializable
{
    /**
     * @var FeeItemSummaryAllOf0[]|null
     */
    private $feeItemsSummary;

    /**
     * @var string|null
     */
    private $requestId;

    /**
     * @var ErrorStatus|null
     */
    private $error;

    /**
     * Returns Fee Items Summary.
     *
     * @return FeeItemSummaryAllOf0[]|null
     */
    public function getFeeItemsSummary(): ?array
    {
        return $this->feeItemsSummary;
    }

    /**
     * Sets Fee Items Summary.
     *
     * @maps FeeItemsSummary
     *
     * @param FeeItemSummaryAllOf0[]|null $feeItemsSummary
     */
    public function setFeeItemsSummary(?array $feeItemsSummary): void
    {
        $this->feeItemsSummary = $feeItemsSummary;
    }

    /**
     * Returns Request Id.
     * A unique request id in GUID format. The value is written to the Shell API Platform audit log for end
     * to end traceability of a request. If a value is not provided by an API client, then a GUID is
     * automatically populated by the Shell API Platform and returned in the API response.
     */
    public function getRequestId(): ?string
    {
        return $this->requestId;
    }

    /**
     * Sets Request Id.
     * A unique request id in GUID format. The value is written to the Shell API Platform audit log for end
     * to end traceability of a request. If a value is not provided by an API client, then a GUID is
     * automatically populated by the Shell API Platform and returned in the API response.
     *
     * @maps RequestId
     */
    public function setRequestId(?string $requestId): void
    {
        $this->requestId = $requestId;
    }

    /**
     * Returns Error.
     */
    public function getError(): ?ErrorStatus
    {
        return $this->error;
    }

    /**
     * Sets Error.
     *
     * @maps Error
     */
    public function setError(?ErrorStatus $error): void
    {
        $this->error = $error;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->feeItemsSummary)) {
            $json['FeeItemsSummary'] = $this->feeItemsSummary;
        }
        if (isset($this->requestId)) {
            $json['RequestId']       = $this->requestId;
        }
        if (isset($this->error)) {
            $json['Error']           = $this->error;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
