<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models;

use stdClass;

class FuelConsumptionResponse implements \JsonSerializable
{
    /**
     * @var FuelConsumptionData[]|null
     */
    private $fuelConsumption;

    /**
     * @var ErrorStatus|null
     */
    private $error;

    /**
     * @var string|null
     */
    private $requestId;

    /**
     * Returns Fuel Consumption.
     *
     * @return FuelConsumptionData[]|null
     */
    public function getFuelConsumption(): ?array
    {
        return $this->fuelConsumption;
    }

    /**
     * Sets Fuel Consumption.
     *
     * @maps FuelConsumption
     *
     * @param FuelConsumptionData[]|null $fuelConsumption
     */
    public function setFuelConsumption(?array $fuelConsumption): void
    {
        $this->fuelConsumption = $fuelConsumption;
    }

    /**
     * Returns Error.
     */
    public function getError(): ?ErrorStatus
    {
        return $this->error;
    }

    /**
     * Sets Error.
     *
     * @maps Error
     */
    public function setError(?ErrorStatus $error): void
    {
        $this->error = $error;
    }

    /**
     * Returns Request Id.
     * API Request Id
     */
    public function getRequestId(): ?string
    {
        return $this->requestId;
    }

    /**
     * Sets Request Id.
     * API Request Id
     *
     * @maps RequestId
     */
    public function setRequestId(?string $requestId): void
    {
        $this->requestId = $requestId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->fuelConsumption)) {
            $json['FuelConsumption'] = $this->fuelConsumption;
        }
        if (isset($this->error)) {
            $json['Error']           = $this->error;
        }
        if (isset($this->requestId)) {
            $json['RequestId']       = $this->requestId;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
