<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models;

use stdClass;

class InvoiceDownloadReq implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $colCoCode;

    /**
     * @var string|null
     */
    private $payerNumber;

    /**
     * @var string[]|null
     */
    private $accountNumber;

    /**
     * @var int[]|null
     */
    private $documentReference;

    /**
     * @var array
     */
    private $invoiceOrSOANumber = [];

    /**
     * Returns Col Co Code.
     * Collecting Company Code of the selected payer.
     *
     * Mandatory
     */
    public function getColCoCode(): ?int
    {
        return $this->colCoCode;
    }

    /**
     * Sets Col Co Code.
     * Collecting Company Code of the selected payer.
     *
     * Mandatory
     *
     * @maps ColCoCode
     */
    public function setColCoCode(?int $colCoCode): void
    {
        $this->colCoCode = $colCoCode;
    }

    /**
     * Returns Payer Number.
     * Payer Number of the selected payer.
     *
     * Mandatory
     *
     * Example: GB000000123
     */
    public function getPayerNumber(): ?string
    {
        return $this->payerNumber;
    }

    /**
     * Sets Payer Number.
     * Payer Number of the selected payer.
     *
     * Mandatory
     *
     * Example: GB000000123
     *
     * @maps PayerNumber
     */
    public function setPayerNumber(?string $payerNumber): void
    {
        $this->payerNumber = $payerNumber;
    }

    /**
     * Returns Account Number.
     * List of Account Numbers of the invoices.
     * Mandatory for customer users else optional.
     *
     * @return string[]|null
     */
    public function getAccountNumber(): ?array
    {
        return $this->accountNumber;
    }

    /**
     * Sets Account Number.
     * List of Account Numbers of the invoices.
     * Mandatory for customer users else optional.
     *
     * @maps AccountNumber
     *
     * @param string[]|null $accountNumber
     */
    public function setAccountNumber(?array $accountNumber): void
    {
        $this->accountNumber = $accountNumber;
    }

    /**
     * Returns Document Reference.
     * Unique reference ids of invoice document (of zip file).
     * Optional if InvoiceOrSOANumber is passed else Mandatory.
     *
     * @return int[]|null
     */
    public function getDocumentReference(): ?array
    {
        return $this->documentReference;
    }

    /**
     * Sets Document Reference.
     * Unique reference ids of invoice document (of zip file).
     * Optional if InvoiceOrSOANumber is passed else Mandatory.
     *
     * @maps DocumentReference
     *
     * @param int[]|null $documentReference
     */
    public function setDocumentReference(?array $documentReference): void
    {
        $this->documentReference = $documentReference;
    }

    /**
     * Returns Invoice or SOA Number.
     * Invoice or the SOA document reference number issued by Card s Platform.
     */
    public function getInvoiceOrSOANumber(): ?string
    {
        if (count($this->invoiceOrSOANumber) == 0) {
            return null;
        }
        return $this->invoiceOrSOANumber['value'];
    }

    /**
     * Sets Invoice or SOA Number.
     * Invoice or the SOA document reference number issued by Card s Platform.
     *
     * @maps InvoiceOrSOANumber
     */
    public function setInvoiceOrSOANumber(?string $invoiceOrSOANumber): void
    {
        $this->invoiceOrSOANumber['value'] = $invoiceOrSOANumber;
    }

    /**
     * Unsets Invoice or SOA Number.
     * Invoice or the SOA document reference number issued by Card s Platform.
     */
    public function unsetInvoiceOrSOANumber(): void
    {
        $this->invoiceOrSOANumber = [];
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['ColCoCode']              = $this->colCoCode;
        $json['PayerNumber']            = $this->payerNumber;
        if (isset($this->accountNumber)) {
            $json['AccountNumber']      = $this->accountNumber;
        }
        if (isset($this->documentReference)) {
            $json['DocumentReference']  = $this->documentReference;
        }
        if (!empty($this->invoiceOrSOANumber)) {
            $json['InvoiceOrSOANumber'] = $this->invoiceOrSOANumber['value'];
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
