<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models;

use stdClass;

class MultiPricedTransactionResponse implements \JsonSerializable
{
    /**
     * @var MultiPricedTransactionResponseTransactionsItems[]|null
     */
    private $transactions;

    /**
     * @var ErrorStatus|null
     */
    private $error;

    /**
     * @var string|null
     */
    private $requestId;

    /**
     * @var int|null
     */
    private $currentPage;

    /**
     * @var int|null
     */
    private $rowCount;

    /**
     * @var int|null
     */
    private $totalPages;

    /**
     * Returns Transactions.
     *
     * @return MultiPricedTransactionResponseTransactionsItems[]|null
     */
    public function getTransactions(): ?array
    {
        return $this->transactions;
    }

    /**
     * Sets Transactions.
     *
     * @maps Transactions
     *
     * @param MultiPricedTransactionResponseTransactionsItems[]|null $transactions
     */
    public function setTransactions(?array $transactions): void
    {
        $this->transactions = $transactions;
    }

    /**
     * Returns Error.
     */
    public function getError(): ?ErrorStatus
    {
        return $this->error;
    }

    /**
     * Sets Error.
     *
     * @maps Error
     */
    public function setError(?ErrorStatus $error): void
    {
        $this->error = $error;
    }

    /**
     * Returns Request Id.
     * API Request Id
     */
    public function getRequestId(): ?string
    {
        return $this->requestId;
    }

    /**
     * Sets Request Id.
     * API Request Id
     *
     * @maps RequestId
     */
    public function setRequestId(?string $requestId): void
    {
        $this->requestId = $requestId;
    }

    /**
     * Returns Current Page.
     * Current Page
     */
    public function getCurrentPage(): ?int
    {
        return $this->currentPage;
    }

    /**
     * Sets Current Page.
     * Current Page
     *
     * @maps CurrentPage
     */
    public function setCurrentPage(?int $currentPage): void
    {
        $this->currentPage = $currentPage;
    }

    /**
     * Returns Row Count.
     * Total row count matched for the given input criteria
     */
    public function getRowCount(): ?int
    {
        return $this->rowCount;
    }

    /**
     * Sets Row Count.
     * Total row count matched for the given input criteria
     *
     * @maps RowCount
     */
    public function setRowCount(?int $rowCount): void
    {
        $this->rowCount = $rowCount;
    }

    /**
     * Returns Total Pages.
     * Calculated page count based on page size from the incoming API request and total number of rows
     * matched for the given input criteria
     */
    public function getTotalPages(): ?int
    {
        return $this->totalPages;
    }

    /**
     * Sets Total Pages.
     * Calculated page count based on page size from the incoming API request and total number of rows
     * matched for the given input criteria
     *
     * @maps TotalPages
     */
    public function setTotalPages(?int $totalPages): void
    {
        $this->totalPages = $totalPages;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->transactions)) {
            $json['Transactions'] = $this->transactions;
        }
        if (isset($this->error)) {
            $json['Error']        = $this->error;
        }
        if (isset($this->requestId)) {
            $json['RequestId']    = $this->requestId;
        }
        if (isset($this->currentPage)) {
            $json['CurrentPage']  = $this->currentPage;
        }
        if (isset($this->rowCount)) {
            $json['RowCount']     = $this->rowCount;
        }
        if (isset($this->totalPages)) {
            $json['TotalPages']   = $this->totalPages;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
