<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models;

use stdClass;

class PriceTransSummaryRequest implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $colCoId;

    /**
     * @var int|null
     */
    private $colCoCode;

    /**
     * @var int|null
     */
    private $payerId;

    /**
     * @var string|null
     */
    private $payerNumber;

    /**
     * @var Accounts|null
     */
    private $accounts;

    /**
     * @var int|null
     */
    private $cardId;

    /**
     * @var string|null
     */
    private $cardPAN;

    /**
     * @var string|null
     */
    private $driverName;

    /**
     * @var string|null
     */
    private $vehicleRegistrationNumber;

    /**
     * @var string|null
     */
    private $invoiceStatus;

    /**
     * @var int|null
     */
    private $productId;

    /**
     * @var string|null
     */
    private $productCode;

    /**
     * @var string|null
     */
    private $purchasedInCountry;

    /**
     * @var int|null
     */
    private $cardGroupId;

    /**
     * @var string|null
     */
    private $fromDate;

    /**
     * @var string|null
     */
    private $toDate;

    /**
     * @var int|null
     */
    private $period;

    /**
     * @var string|null
     */
    private $siteCode;

    /**
     * @var int|null
     */
    private $siteGroupId;

    /**
     * @var string|null
     */
    private $postingDateFrom;

    /**
     * @var string|null
     */
    private $postingDateTo;

    /**
     * @var string|null
     */
    private $salesItemId;

    /**
     * @var string|null
     */
    private $transactionId;

    /**
     * @var string|null
     */
    private $invoiceDate;

    /**
     * @var string|null
     */
    private $invoiceNumber;

    /**
     * @var bool|null
     */
    private $validInvoiceDateOnly;

    /**
     * @var string|null
     */
    private $invoiceFromDate;

    /**
     * @var string|null
     */
    private $invoiceToDate;

    /**
     * @var bool|null
     */
    private $fuelOnly;

    /**
     * @var bool|null
     */
    private $includeFees;

    /**
     * Returns Col Co Id.
     * Collecting Company Id of the selected payer.
     *
     * Optional if ColCoCode is passed else Mandatory.
     *
     * Example:
     *
     * 1 for Philippines
     *
     * 5 for UK
     */
    public function getColCoId(): ?int
    {
        return $this->colCoId;
    }

    /**
     * Sets Col Co Id.
     * Collecting Company Id of the selected payer.
     *
     * Optional if ColCoCode is passed else Mandatory.
     *
     * Example:
     *
     * 1 for Philippines
     *
     * 5 for UK
     *
     * @maps ColCoId
     */
    public function setColCoId(?int $colCoId): void
    {
        $this->colCoId = $colCoId;
    }

    /**
     * Returns Col Co Code.
     * Collecting Company Code  of the selected payer.
     *
     * Mandatory for serviced OUs such as Romania, Latvia, Lithuania, Estonia, Ukraine etc. It is optional
     * for other countries if ColCoID is provided.
     *
     * Example:
     *
     * 86 for Philippines
     *
     * 5 for UK
     */
    public function getColCoCode(): ?int
    {
        return $this->colCoCode;
    }

    /**
     * Sets Col Co Code.
     * Collecting Company Code  of the selected payer.
     *
     * Mandatory for serviced OUs such as Romania, Latvia, Lithuania, Estonia, Ukraine etc. It is optional
     * for other countries if ColCoID is provided.
     *
     * Example:
     *
     * 86 for Philippines
     *
     * 5 for UK
     *
     * @maps ColCoCode
     */
    public function setColCoCode(?int $colCoCode): void
    {
        $this->colCoCode = $colCoCode;
    }

    /**
     * Returns Payer Id.
     * Payer Id  of the selected payer.
     *
     * Optional if PayerNumber is passed else Mandatory
     */
    public function getPayerId(): ?int
    {
        return $this->payerId;
    }

    /**
     * Sets Payer Id.
     * Payer Id  of the selected payer.
     *
     * Optional if PayerNumber is passed else Mandatory
     *
     * @maps PayerId
     */
    public function setPayerId(?int $payerId): void
    {
        $this->payerId = $payerId;
    }

    /**
     * Returns Payer Number.
     * Payer Number (Ex: GB000000123) of the selected payer.
     *
     * Optional if PayerId is passed else Mandatory
     *
     * Example: GB000000123
     */
    public function getPayerNumber(): ?string
    {
        return $this->payerNumber;
    }

    /**
     * Sets Payer Number.
     * Payer Number (Ex: GB000000123) of the selected payer.
     *
     * Optional if PayerId is passed else Mandatory
     *
     * Example: GB000000123
     *
     * @maps PayerNumber
     */
    public function setPayerNumber(?string $payerNumber): void
    {
        $this->payerNumber = $payerNumber;
    }

    /**
     * Returns Accounts.
     */
    public function getAccounts(): ?Accounts
    {
        return $this->accounts;
    }

    /**
     * Sets Accounts.
     *
     * @maps Accounts
     */
    public function setAccounts(?Accounts $accounts): void
    {
        $this->accounts = $accounts;
    }

    /**
     * Returns Card Id.
     * Card Id (i.e. Unique Card Id in GFN)
     *
     * Optional
     *
     * When both Card Id and Card PAN are not present on request, the response will have transactions of
     * all cards under the selected payer or account
     */
    public function getCardId(): ?int
    {
        return $this->cardId;
    }

    /**
     * Sets Card Id.
     * Card Id (i.e. Unique Card Id in GFN)
     *
     * Optional
     *
     * When both Card Id and Card PAN are not present on request, the response will have transactions of
     * all cards under the selected payer or account
     *
     * @maps CardId
     */
    public function setCardId(?int $cardId): void
    {
        $this->cardId = $cardId;
    }

    /**
     * Returns Card PAN.
     * Full Card PAN
     *
     * Optional
     *
     * When both Card Id and Card PAN are not present on request, the response will have transactions of
     * all cards under the selected payer or account.
     */
    public function getCardPAN(): ?string
    {
        return $this->cardPAN;
    }

    /**
     * Sets Card PAN.
     * Full Card PAN
     *
     * Optional
     *
     * When both Card Id and Card PAN are not present on request, the response will have transactions of
     * all cards under the selected payer or account.
     *
     * @maps CardPAN
     */
    public function setCardPAN(?string $cardPAN): void
    {
        $this->cardPAN = $cardPAN;
    }

    /**
     * Returns Driver Name.
     * Driver Name (of Card record)
     *
     * Optional
     *
     * Minimum of 4 characters should be provided else not considered
     *
     * Transactions of the card having the entered value at any part of the Driver Name will be returned
     */
    public function getDriverName(): ?string
    {
        return $this->driverName;
    }

    /**
     * Sets Driver Name.
     * Driver Name (of Card record)
     *
     * Optional
     *
     * Minimum of 4 characters should be provided else not considered
     *
     * Transactions of the card having the entered value at any part of the Driver Name will be returned
     *
     * @maps DriverName
     */
    public function setDriverName(?string $driverName): void
    {
        $this->driverName = $driverName;
    }

    /**
     * Returns Vehicle Registration Number.
     * Vehicle Registration (of Card record)
     *
     * Optional
     *
     * Minimum of 4 characters should be provided else not considered
     *
     * Transactions of the card having the entered value at any part of the VRN will be returned
     */
    public function getVehicleRegistrationNumber(): ?string
    {
        return $this->vehicleRegistrationNumber;
    }

    /**
     * Sets Vehicle Registration Number.
     * Vehicle Registration (of Card record)
     *
     * Optional
     *
     * Minimum of 4 characters should be provided else not considered
     *
     * Transactions of the card having the entered value at any part of the VRN will be returned
     *
     * @maps VehicleRegistrationNumber
     */
    public function setVehicleRegistrationNumber(?string $vehicleRegistrationNumber): void
    {
        $this->vehicleRegistrationNumber = $vehicleRegistrationNumber;
    }

    /**
     * Returns Invoice Status.
     * Invoice status of the transactions.
     *
     * Mandatory
     *
     * Possible options:
     *
     * I - Invoiced
     *
     * U – Un-Invoiced
     *
     * A – All
     */
    public function getInvoiceStatus(): ?string
    {
        return $this->invoiceStatus;
    }

    /**
     * Sets Invoice Status.
     * Invoice status of the transactions.
     *
     * Mandatory
     *
     * Possible options:
     *
     * I - Invoiced
     *
     * U – Un-Invoiced
     *
     * A – All
     *
     * @maps InvoiceStatus
     */
    public function setInvoiceStatus(?string $invoiceStatus): void
    {
        $this->invoiceStatus = $invoiceStatus;
    }

    /**
     * Returns Product Id.
     * Product Id
     *
     * Example:
     *
     * 21 Unleaded - High octane
     *
     * 22 Unleaded - Medium octane
     *
     * 23 Unleaded - Low octane
     *
     * 24 Unleaded Environmental
     */
    public function getProductId(): ?int
    {
        return $this->productId;
    }

    /**
     * Sets Product Id.
     * Product Id
     *
     * Example:
     *
     * 21 Unleaded - High octane
     *
     * 22 Unleaded - Medium octane
     *
     * 23 Unleaded - Low octane
     *
     * 24 Unleaded Environmental
     *
     * @maps ProductId
     */
    public function setProductId(?int $productId): void
    {
        $this->productId = $productId;
    }

    /**
     * Returns Product Code.
     * Product Code – Global as per GFN configuration
     *
     * Optional
     *
     * Max Length: 8
     *
     * Example:
     *
     * 10 TMF Charges
     *
     * 11 Tunnel/Bridges
     *
     * 12 Motorway toll
     *
     * 13 Ferries
     */
    public function getProductCode(): ?string
    {
        return $this->productCode;
    }

    /**
     * Sets Product Code.
     * Product Code – Global as per GFN configuration
     *
     * Optional
     *
     * Max Length: 8
     *
     * Example:
     *
     * 10 TMF Charges
     *
     * 11 Tunnel/Bridges
     *
     * 12 Motorway toll
     *
     * 13 Ferries
     *
     * @maps ProductCode
     */
    public function setProductCode(?string $productCode): void
    {
        $this->productCode = $productCode;
    }

    /**
     * Returns Purchased in Country.
     * ISO Country Code (ex: UK, FR)
     *
     *
     *
     * Note: If IncludeFees is true then this filter will be ignored
     */
    public function getPurchasedInCountry(): ?string
    {
        return $this->purchasedInCountry;
    }

    /**
     * Sets Purchased in Country.
     * ISO Country Code (ex: UK, FR)
     *
     *
     *
     * Note: If IncludeFees is true then this filter will be ignored
     *
     * @maps PurchasedInCountry
     */
    public function setPurchasedInCountry(?string $purchasedInCountry): void
    {
        $this->purchasedInCountry = $purchasedInCountry;
    }

    /**
     * Returns Card Group Id.
     * Card Group Id in GFN
     */
    public function getCardGroupId(): ?int
    {
        return $this->cardGroupId;
    }

    /**
     * Sets Card Group Id.
     * Card Group Id in GFN
     *
     * @maps CardGroupId
     */
    public function setCardGroupId(?int $cardGroupId): void
    {
        $this->cardGroupId = $cardGroupId;
    }

    /**
     * Returns From Date.
     * Transactions from Date/Time.
     *
     * Optional – When provided, it should be with in last 24 months.
     *
     *
     *
     * Format: yyyyMMdd
     */
    public function getFromDate(): ?string
    {
        return $this->fromDate;
    }

    /**
     * Sets From Date.
     * Transactions from Date/Time.
     *
     * Optional – When provided, it should be with in last 24 months.
     *
     *
     *
     * Format: yyyyMMdd
     *
     * @maps FromDate
     */
    public function setFromDate(?string $fromDate): void
    {
        $this->fromDate = $fromDate;
    }

    /**
     * Returns To Date.
     * Transactions to Date/Time.
     *
     * Optional- Refer introduction section of this operation for the priority and sequence of different
     * date and invoice number filters that are conditionally applied.
     *
     * Note:
     *
     * 1) When the value is blank and FromDate is provided on the input, all transactions took place
     * 210(Configurable) days after the given FromDate is returned.
     *
     * 2) Difference between FromDate and ToDate cannot be more than 210 (Configurable) days.
     *
     *
     *
     * Format: yyyyMMdd
     */
    public function getToDate(): ?string
    {
        return $this->toDate;
    }

    /**
     * Sets To Date.
     * Transactions to Date/Time.
     *
     * Optional- Refer introduction section of this operation for the priority and sequence of different
     * date and invoice number filters that are conditionally applied.
     *
     * Note:
     *
     * 1) When the value is blank and FromDate is provided on the input, all transactions took place
     * 210(Configurable) days after the given FromDate is returned.
     *
     * 2) Difference between FromDate and ToDate cannot be more than 210 (Configurable) days.
     *
     *
     *
     * Format: yyyyMMdd
     *
     * @maps ToDate
     */
    public function setToDate(?string $toDate): void
    {
        $this->toDate = $toDate;
    }

    /**
     * Returns Period.
     * Transactions Period.
     *
     * Possible values are:
     *
     * 1. Last 7 Days
     *
     * 2. Last 30 Days
     *
     * 3. Last 90 Days
     *
     * Optional - Refer introduction section of this operation for the priority and sequence of different
     * date and invoice number filters that are conditionally applied.
     */
    public function getPeriod(): ?int
    {
        return $this->period;
    }

    /**
     * Sets Period.
     * Transactions Period.
     *
     * Possible values are:
     *
     * 1. Last 7 Days
     *
     * 2. Last 30 Days
     *
     * 3. Last 90 Days
     *
     * Optional - Refer introduction section of this operation for the priority and sequence of different
     * date and invoice number filters that are conditionally applied.
     *
     * @maps Period
     */
    public function setPeriod(?int $period): void
    {
        $this->period = $period;
    }

    /**
     * Returns Site Code.
     * Site Code as configured in GFN
     *
     * Example:
     *
     * 050001 - CHARNOCK RICHARD NTHBOUND MWSA 0755
     *
     * 050002 - CHARNOCK RICHARD STHBOUND MWSA 0755
     *
     * 050005 - HARTSHEAD MOOR EASTBOUND MWSA 0761.
     *
     * 050006 - HARTSHEAD MOOR WESTBOUND MWSA.
     *
     * Note: If IncludeFees is true then this filter will be ignored
     */
    public function getSiteCode(): ?string
    {
        return $this->siteCode;
    }

    /**
     * Sets Site Code.
     * Site Code as configured in GFN
     *
     * Example:
     *
     * 050001 - CHARNOCK RICHARD NTHBOUND MWSA 0755
     *
     * 050002 - CHARNOCK RICHARD STHBOUND MWSA 0755
     *
     * 050005 - HARTSHEAD MOOR EASTBOUND MWSA 0761.
     *
     * 050006 - HARTSHEAD MOOR WESTBOUND MWSA.
     *
     * Note: If IncludeFees is true then this filter will be ignored
     *
     * @maps SiteCode
     */
    public function setSiteCode(?string $siteCode): void
    {
        $this->siteCode = $siteCode;
    }

    /**
     * Returns Site Group Id.
     * Site Group Id in GFN
     *
     * Optional
     *
     * Example: 202
     *
     * Note: If IncludeFees is true then this filter will be ignored
     */
    public function getSiteGroupId(): ?int
    {
        return $this->siteGroupId;
    }

    /**
     * Sets Site Group Id.
     * Site Group Id in GFN
     *
     * Optional
     *
     * Example: 202
     *
     * Note: If IncludeFees is true then this filter will be ignored
     *
     * @maps SiteGroupId
     */
    public function setSiteGroupId(?int $siteGroupId): void
    {
        $this->siteGroupId = $siteGroupId;
    }

    /**
     * Returns Posting Date From.
     * Transaction Posting Date/time in the Cards Platform - From Date/time.
     *
     *
     *
     * Note:
     *
     * 1) When the value of both PostingDateFrom and PostingDateTo are present in the request then the
     * value of PostingDateFrom must be less than PostingDateTo.
     *
     * 2) If IncludeFees is true then this filter will be ignored
     *
     * Format: yyyyMMdd HH:mm:ss
     */
    public function getPostingDateFrom(): ?string
    {
        return $this->postingDateFrom;
    }

    /**
     * Sets Posting Date From.
     * Transaction Posting Date/time in the Cards Platform - From Date/time.
     *
     *
     *
     * Note:
     *
     * 1) When the value of both PostingDateFrom and PostingDateTo are present in the request then the
     * value of PostingDateFrom must be less than PostingDateTo.
     *
     * 2) If IncludeFees is true then this filter will be ignored
     *
     * Format: yyyyMMdd HH:mm:ss
     *
     * @maps PostingDateFrom
     */
    public function setPostingDateFrom(?string $postingDateFrom): void
    {
        $this->postingDateFrom = $postingDateFrom;
    }

    /**
     * Returns Posting Date To.
     * Transaction Posting Date/time in the Cards Platform – To Date/time.
     *
     *
     *
     * Note:
     *
     * 1) If IncludeFees is true then this filter will be ignored.
     *
     * 2) When the value of both PostingDateFrom and PostingDateTo are present in the request then the
     * value of PostingDateFrom must be less than PostingDateTo.
     *
     * Format: yyyyMMdd HH:mm:ss
     */
    public function getPostingDateTo(): ?string
    {
        return $this->postingDateTo;
    }

    /**
     * Sets Posting Date To.
     * Transaction Posting Date/time in the Cards Platform – To Date/time.
     *
     *
     *
     * Note:
     *
     * 1) If IncludeFees is true then this filter will be ignored.
     *
     * 2) When the value of both PostingDateFrom and PostingDateTo are present in the request then the
     * value of PostingDateFrom must be less than PostingDateTo.
     *
     * Format: yyyyMMdd HH:mm:ss
     *
     * @maps PostingDateTo
     */
    public function setPostingDateTo(?string $postingDateTo): void
    {
        $this->postingDateTo = $postingDateTo;
    }

    /**
     * Returns Sales Item Id.
     * Unique SalesItemId (Either Billed on Unbilled)
     *
     * Optional
     *
     * Note: If IncludeFees is true then this filter will be ignored
     */
    public function getSalesItemId(): ?string
    {
        return $this->salesItemId;
    }

    /**
     * Sets Sales Item Id.
     * Unique SalesItemId (Either Billed on Unbilled)
     *
     * Optional
     *
     * Note: If IncludeFees is true then this filter will be ignored
     *
     * @maps SalesItemId
     */
    public function setSalesItemId(?string $salesItemId): void
    {
        $this->salesItemId = $salesItemId;
    }

    /**
     * Returns Transaction Id.
     * Unique Transaction Id
     *
     * Optional
     *
     * Note: If IncludeFees is true then this filter will be ignored
     */
    public function getTransactionId(): ?string
    {
        return $this->transactionId;
    }

    /**
     * Sets Transaction Id.
     * Unique Transaction Id
     *
     * Optional
     *
     * Note: If IncludeFees is true then this filter will be ignored
     *
     * @maps TransactionId
     */
    public function setTransactionId(?string $transactionId): void
    {
        $this->transactionId = $transactionId;
    }

    /**
     * Returns Invoice Date.
     * Invoice Date.
     *
     * Optional
     *
     * Note:
     *
     * 1) If value is not blank then the system will ignore the InvoiceStatus parameter and it will return
     * all the billed transactions for the given invoice date.
     *
     *
     *
     * Format: yyyyMMdd
     */
    public function getInvoiceDate(): ?string
    {
        return $this->invoiceDate;
    }

    /**
     * Sets Invoice Date.
     * Invoice Date.
     *
     * Optional
     *
     * Note:
     *
     * 1) If value is not blank then the system will ignore the InvoiceStatus parameter and it will return
     * all the billed transactions for the given invoice date.
     *
     *
     *
     * Format: yyyyMMdd
     *
     * @maps InvoiceDate
     */
    public function setInvoiceDate(?string $invoiceDate): void
    {
        $this->invoiceDate = $invoiceDate;
    }

    /**
     * Returns Invoice Number.
     * Invoice Number.
     *
     * Optional
     *
     * Note:
     *
     * 1) If value is not blank then the system will ignore the InvoiceStatus parameter and it will return
     * all the billed transactions for the given invoice date.
     */
    public function getInvoiceNumber(): ?string
    {
        return $this->invoiceNumber;
    }

    /**
     * Sets Invoice Number.
     * Invoice Number.
     *
     * Optional
     *
     * Note:
     *
     * 1) If value is not blank then the system will ignore the InvoiceStatus parameter and it will return
     * all the billed transactions for the given invoice date.
     *
     * @maps InvoiceNumber
     */
    public function setInvoiceNumber(?string $invoiceNumber): void
    {
        $this->invoiceNumber = $invoiceNumber;
    }

    /**
     * Returns Valid Invoice Date Only.
     * True/False
     *
     * Optional
     *
     * Default value: True.
     *
     * When passed as ‘True’ the transactions records with report date not equal to 9999-12-30 will be
     * returned.
     *
     * When passed as ‘False’ the above condition will not be checked.
     */
    public function getValidInvoiceDateOnly(): ?bool
    {
        return $this->validInvoiceDateOnly;
    }

    /**
     * Sets Valid Invoice Date Only.
     * True/False
     *
     * Optional
     *
     * Default value: True.
     *
     * When passed as ‘True’ the transactions records with report date not equal to 9999-12-30 will be
     * returned.
     *
     * When passed as ‘False’ the above condition will not be checked.
     *
     * @maps ValidInvoiceDateOnly
     */
    public function setValidInvoiceDateOnly(?bool $validInvoiceDateOnly): void
    {
        $this->validInvoiceDateOnly = $validInvoiceDateOnly;
    }

    /**
     * Returns Invoice From Date.
     * Start date for transaction search by invoice date.
     *
     * Optional
     *
     * Note:
     *
     *
     *
     * 1) Value should be with in last 24 months (if provided).
     *
     * 2) Maximum of 90(Configurable) day’s duration allowed per search.
     *
     * 3) When provided, InvoiceFromDate has to be less than or equal to InvoiceToDate.
     *
     * Format: yyyyMMdd
     */
    public function getInvoiceFromDate(): ?string
    {
        return $this->invoiceFromDate;
    }

    /**
     * Sets Invoice From Date.
     * Start date for transaction search by invoice date.
     *
     * Optional
     *
     * Note:
     *
     *
     *
     * 1) Value should be with in last 24 months (if provided).
     *
     * 2) Maximum of 90(Configurable) day’s duration allowed per search.
     *
     * 3) When provided, InvoiceFromDate has to be less than or equal to InvoiceToDate.
     *
     * Format: yyyyMMdd
     *
     * @maps InvoiceFromDate
     */
    public function setInvoiceFromDate(?string $invoiceFromDate): void
    {
        $this->invoiceFromDate = $invoiceFromDate;
    }

    /**
     * Returns Invoice to Date.
     * End date for transaction search by invoice date.
     *
     * Optional
     *
     * Note:
     *
     *
     *
     * 1) When InvoiceFromDate is provided and InvoiceToDate is null, then InvoiceToDate will be calculated
     * as (InvoiceFromDate + 90 days) or (CurrentDate) whichever is lesser.
     *
     * Format: yyyyMMdd
     */
    public function getInvoiceToDate(): ?string
    {
        return $this->invoiceToDate;
    }

    /**
     * Sets Invoice to Date.
     * End date for transaction search by invoice date.
     *
     * Optional
     *
     * Note:
     *
     *
     *
     * 1) When InvoiceFromDate is provided and InvoiceToDate is null, then InvoiceToDate will be calculated
     * as (InvoiceFromDate + 90 days) or (CurrentDate) whichever is lesser.
     *
     * Format: yyyyMMdd
     *
     * @maps InvoiceToDate
     */
    public function setInvoiceToDate(?string $invoiceToDate): void
    {
        $this->invoiceToDate = $invoiceToDate;
    }

    /**
     * Returns Fuel Only.
     * True/False
     *
     * Optional
     *
     * Default value: False.
     *
     * When passed as ‘True’ Only returned records with Fuel transactions.
     *
     * When passed as ‘False’ the above condition will not be checked.
     */
    public function getFuelOnly(): ?bool
    {
        return $this->fuelOnly;
    }

    /**
     * Sets Fuel Only.
     * True/False
     *
     * Optional
     *
     * Default value: False.
     *
     * When passed as ‘True’ Only returned records with Fuel transactions.
     *
     * When passed as ‘False’ the above condition will not be checked.
     *
     * @maps FuelOnly
     */
    public function setFuelOnly(?bool $fuelOnly): void
    {
        $this->fuelOnly = $fuelOnly;
    }

    /**
     * Returns Include Fees.
     * True/False
     *
     * Optional
     *
     * Default value: False
     *
     * When passed as ‘True’ then  ignore few filters, all sales items along with fees included on the same
     * response
     */
    public function getIncludeFees(): ?bool
    {
        return $this->includeFees;
    }

    /**
     * Sets Include Fees.
     * True/False
     *
     * Optional
     *
     * Default value: False
     *
     * When passed as ‘True’ then  ignore few filters, all sales items along with fees included on the same
     * response
     *
     * @maps IncludeFees
     */
    public function setIncludeFees(?bool $includeFees): void
    {
        $this->includeFees = $includeFees;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->colCoId)) {
            $json['ColCoId']                   = $this->colCoId;
        }
        if (isset($this->colCoCode)) {
            $json['ColCoCode']                 = $this->colCoCode;
        }
        if (isset($this->payerId)) {
            $json['PayerId']                   = $this->payerId;
        }
        if (isset($this->payerNumber)) {
            $json['PayerNumber']               = $this->payerNumber;
        }
        if (isset($this->accounts)) {
            $json['Accounts']                  = $this->accounts;
        }
        if (isset($this->cardId)) {
            $json['CardId']                    = $this->cardId;
        }
        if (isset($this->cardPAN)) {
            $json['CardPAN']                   = $this->cardPAN;
        }
        if (isset($this->driverName)) {
            $json['DriverName']                = $this->driverName;
        }
        if (isset($this->vehicleRegistrationNumber)) {
            $json['VehicleRegistrationNumber'] = $this->vehicleRegistrationNumber;
        }
        if (isset($this->invoiceStatus)) {
            $json['InvoiceStatus']             = $this->invoiceStatus;
        }
        if (isset($this->productId)) {
            $json['ProductId']                 = $this->productId;
        }
        if (isset($this->productCode)) {
            $json['ProductCode']               = $this->productCode;
        }
        if (isset($this->purchasedInCountry)) {
            $json['PurchasedInCountry']        = $this->purchasedInCountry;
        }
        if (isset($this->cardGroupId)) {
            $json['CardGroupId']               = $this->cardGroupId;
        }
        if (isset($this->fromDate)) {
            $json['FromDate']                  = $this->fromDate;
        }
        if (isset($this->toDate)) {
            $json['ToDate']                    = $this->toDate;
        }
        if (isset($this->period)) {
            $json['Period']                    = $this->period;
        }
        if (isset($this->siteCode)) {
            $json['SiteCode']                  = $this->siteCode;
        }
        if (isset($this->siteGroupId)) {
            $json['SiteGroupId']               = $this->siteGroupId;
        }
        if (isset($this->postingDateFrom)) {
            $json['PostingDateFrom']           = $this->postingDateFrom;
        }
        if (isset($this->postingDateTo)) {
            $json['PostingDateTo']             = $this->postingDateTo;
        }
        if (isset($this->salesItemId)) {
            $json['SalesItemId']               = $this->salesItemId;
        }
        if (isset($this->transactionId)) {
            $json['TransactionId']             = $this->transactionId;
        }
        if (isset($this->invoiceDate)) {
            $json['InvoiceDate']               = $this->invoiceDate;
        }
        if (isset($this->invoiceNumber)) {
            $json['InvoiceNumber']             = $this->invoiceNumber;
        }
        if (isset($this->validInvoiceDateOnly)) {
            $json['ValidInvoiceDateOnly']      = $this->validInvoiceDateOnly;
        }
        if (isset($this->invoiceFromDate)) {
            $json['InvoiceFromDate']           = $this->invoiceFromDate;
        }
        if (isset($this->invoiceToDate)) {
            $json['InvoiceToDate']             = $this->invoiceToDate;
        }
        if (isset($this->fuelOnly)) {
            $json['FuelOnly']                  = $this->fuelOnly;
        }
        if (isset($this->includeFees)) {
            $json['IncludeFees']               = $this->includeFees;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
