<?php

declare(strict_types=1);

/*
 * ShellDataReportingAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellDataReportingAPIsLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Invoice status of the transactions. Mandatory Possible options:I - Invoiced, U – Un-Invoiced, A –
 * All
 */
class PricedTransactionReqV2InvoiceStatusEnum
{
    public const I = 'I';

    public const U = 'U';

    public const A = 'A';

    private const _ALL_VALUES = [self::I, self::U, self::A];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for PricedTransactionReqV2InvoiceStatusEnum.");
    }
}
